config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :invoices
  resources :items
  resources :customers
  resources :conmutadors
  resources :mintests
  resources :tests
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :manufacturers
  resources :orders
  resources :devise_models
  resources :providers
  resources :families

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'admin', to: 'admin/dashboard#index', as: 'admin'

  root 'conmutadors#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/build.rb
class Build < ApplicationRecord
  has_many :parts
  belongs_to :devise_model

  #Validación de campos
  validates :imei, presence: true
  validates :NumeroSerie, presence: true
  validates :imei , length: {in: 14..15}
  validates :imei, numericality: {only_integer: true}
  validates :imei, uniqueness: true

  # def disp_imei
  # 	"#{build.nombrecomercial_modelo} - #{build.imei}"
  # end
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/conmutador.rb
class Conmutador < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :invoices
end

app/models/devise_model.rb
class DeviseModel < ApplicationRecord
  belongs_to :manufacturer
  has_many :parts, dependent: :destroy

  accepts_nested_attributes_for :parts
  def name
  	return self.nombrecomercial_modelo
  end
end

app/models/family.rb
class Family < ApplicationRecord
	has_many :manufacturers , dependent: :destroy
	def name
		return self.nombre_familia
	end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :items, inverse_of: :invoice

  # Acepta atributos anidades de los items que contiene la factura
  accepts_nested_attributes_for :items 
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :invoice	
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  belongs_to :family
  def name
  	return self.nombre_fabricante
  end
end

app/models/mintest.rb
class Mintest < ApplicationRecord
	has_and_belongs_to_many :tests
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :provider
  has_many :parts , :dependent => :destroy

  accepts_nested_attributes_for :parts

  def name
  	fp = self.fecha_pedido.to_s
  	imp = self.valorPedido
  	str = ""

  	str << fp <<" : "<< imp	<<"€"
  	return str
  end
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :devise_model
  belongs_to :order
  has_and_belongs_to_many :tests

  accepts_nested_attributes_for :devise_model
  
  def name
  	return self.nombre_parte
  end
end

app/models/provider.rb
class Provider < ApplicationRecord
	def name
		return self.nombre_proveedor
	end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :build
  belongs_to :devise_model
  has_and_belongs_to_many :mintests

  #validaciones antes de poder escribir en la BD
  validates :devise_model, presence: true
  validates :build, presence: true
  validates :estado , acceptance: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/devise_models_controller.rb
class DeviseModelsController < ApplicationController
  before_action :set_devise_model, only: [:show, :edit, :update, :destroy]

  # GET /devise_models
  # GET /devise_models.json
  def index
    @devise_models = DeviseModel.all
  end

  # GET /devise_models/1
  # GET /devise_models/1.json
  def show
  end

  # GET /devise_models/new
  def new
    @devise_model = DeviseModel.new
  end

  # GET /devise_models/1/edit
  def edit
  end

  # POST /devise_models
  # POST /devise_models.json
  def create
    @devise_model = DeviseModel.new(devise_model_params)

    respond_to do |format|
      if @devise_model.save
        format.html { redirect_to @devise_model, notice: 'Devise model was successfully created.' }
        format.json { render :show, status: :created, location: @devise_model }
      else
        format.html { render :new }
        format.json { render json: @devise_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devise_models/1
  # PATCH/PUT /devise_models/1.json
  def update
    respond_to do |format|
      if @devise_model.update(devise_model_params)
        format.html { redirect_to @devise_model, notice: 'Devise model was successfully updated.' }
        format.json { render :show, status: :ok, location: @devise_model }
      else
        format.html { render :edit }
        format.json { render json: @devise_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devise_models/1
  # DELETE /devise_models/1.json
  def destroy
    @devise_model.destroy
    respond_to do |format|
      format.html { redirect_to devise_models_url, notice: 'Devise model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_devise_model
      @devise_model = DeviseModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def devise_model_params
      params.require(:devise_model).permit(:nombrecomercial_modelo, :manufacturer_id, devise_model_attributes:[:id,:nombreComun_parte,:precio_parte,:_destroy])
    end
end

app/helpers/devise_models_helper.rb
module DeviseModelsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/devise_models/_form.html.erb
<%= simple_form_for(@devise_model) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombrecomercial_modelo %>
    <%= f.association :manufacturer, label_method: :nombre_fabricante %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Crear Nuevo Modelo", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/devise_models/edit.html.erb
<h1>Editing Devise Model</h1>

<%= render 'form', devise_model: @devise_model %>

<%= link_to 'Show', @devise_model %> |
<%= link_to 'Back', devise_models_path %>

app/views/devise_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devise Models</h1>

<table>
  <thead>
    <tr>
      <th>Nombrecomercial modelo</th>
      <th>Manufacturer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devise_models.each do |devise_model| %>
      <tr>
        <td><%= devise_model.nombrecomercial_modelo %></td>
        <td><%= devise_model.manufacturer %></td>
        <td><%= link_to 'Show', devise_model %></td>
        <td><%= link_to 'Edit', edit_devise_model_path(devise_model) %></td>
        <td><%= link_to 'Destroy', devise_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Devise Model', new_devise_model_path %>

app/views/devise_models/new.html.erb
<div class="container">
	<h1>Nuevo Móvil - Nombre comercial</h1>

	<%= render 'form', devise_model: @devise_model %>

	<%= link_to 'Back', devise_models_path %>

</div>

app/views/devise_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombrecomercial modelo:</strong>
  <%= @devise_model.nombrecomercial_modelo %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @devise_model.manufacturer %>
</p>

<%= link_to 'Edit', edit_devise_model_path(@devise_model) %> |
<%= link_to 'Back', devise_models_path %>