config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :invoices
  resources :items
  resources :customers
  resources :conmutadors
  resources :mintests
  resources :tests
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :manufacturers
  resources :orders
  resources :devise_models
  resources :providers
  resources :families

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'admin', to: 'admin/dashboard#index', as: 'admin'

  root 'conmutadors#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/build.rb
class Build < ApplicationRecord
  has_many :parts
  belongs_to :devise_model

  #Validación de campos
  validates :imei, presence: true
  validates :NumeroSerie, presence: true
  validates :imei , length: {in: 14..15}
  validates :imei, numericality: {only_integer: true}
  validates :imei, uniqueness: true

  # def disp_imei
  # 	"#{build.nombrecomercial_modelo} - #{build.imei}"
  # end
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/conmutador.rb
class Conmutador < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :invoices
end

app/models/devise_model.rb
class DeviseModel < ApplicationRecord
  belongs_to :manufacturer
  has_many :parts, dependent: :destroy

  accepts_nested_attributes_for :parts
  def name
  	return self.nombrecomercial_modelo
  end
end

app/models/family.rb
class Family < ApplicationRecord
	has_many :manufacturers , dependent: :destroy
	def name
		return self.nombre_familia
	end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :items, inverse_of: :invoice

  # Acepta atributos anidades de los items que contiene la factura
  accepts_nested_attributes_for :items 
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :invoice	
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  belongs_to :family
  def name
  	return self.nombre_fabricante
  end
end

app/models/mintest.rb
class Mintest < ApplicationRecord
	has_and_belongs_to_many :tests
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :provider
  has_many :parts , :dependent => :destroy

  accepts_nested_attributes_for :parts

  def name
  	fp = self.fecha_pedido.to_s
  	imp = self.valorPedido
  	str = ""

  	str << fp <<" : "<< imp	<<"€"
  	return str
  end
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :devise_model
  belongs_to :order
  has_and_belongs_to_many :tests

  accepts_nested_attributes_for :devise_model
  
  def name
  	return self.nombre_parte
  end
end

app/models/provider.rb
class Provider < ApplicationRecord
	def name
		return self.nombre_proveedor
	end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :build
  belongs_to :devise_model
  has_and_belongs_to_many :mintests

  #validaciones antes de poder escribir en la BD
  validates :devise_model, presence: true
  validates :build, presence: true
  validates :estado , acceptance: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/mintests_controller.rb
class MintestsController < InheritedResources::Base

  private

    def mintest_params
      params.require(:mintest).permit(:nombre, :descripcion)
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mintests_helper.rb
module MintestsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/mintests/_form.html.erb
<%= simple_form_for(@mintest) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mintests/edit.html.erb
<h1>Editing Mintest</h1>

<%= render 'form', mintest: @mintest %>

<%= link_to 'Show', @mintest %> |
<%= link_to 'Back', mintests_path %>

app/views/mintests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mini testeos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mintests.each do |mintest| %>
      <tr>
        <td><%= mintest.nombre %></td>
        <td><%= mintest.descripcion %></td>
        <td><%= link_to 'Ver', mintest, :class => 'btn btn-info' %></td>
        <td><%= link_to 'Editar', edit_mintest_path(mintest) ,:class => 'btn btn-warning'%></td>
        <td><%= link_to 'Borrar', mintest, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-danger'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mintest', new_mintest_path, :class => 'btn btn-success' %>
<%= link_to 'Test Gral' , tests_path , :class => 'btn btn-primary'%>

app/views/mintests/new.html.erb
<h1>New Mintest</h1>

<%= render 'form', mintest: @mintest %>

<%= link_to 'Back', mintests_path %>

app/views/mintests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @mintest.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @mintest.descripcion %>
</p>

<%= link_to 'Edit', edit_mintest_path(@mintest) %> |
<%= link_to 'Back', mintests_path %>