config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :invoices
  resources :items
  resources :customers
  resources :conmutadors
  resources :mintests
  resources :tests
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :manufacturers
  resources :orders
  resources :devise_models
  resources :providers
  resources :families

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'admin', to: 'admin/dashboard#index', as: 'admin'

  root 'conmutadors#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/build.rb
class Build < ApplicationRecord
  has_many :parts
  belongs_to :devise_model

  #Validación de campos
  validates :imei, presence: true
  validates :NumeroSerie, presence: true
  validates :imei , length: {in: 14..15}
  validates :imei, numericality: {only_integer: true}
  validates :imei, uniqueness: true

  # def disp_imei
  # 	"#{build.nombrecomercial_modelo} - #{build.imei}"
  # end
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/conmutador.rb
class Conmutador < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :invoices
end

app/models/devise_model.rb
class DeviseModel < ApplicationRecord
  belongs_to :manufacturer
  has_many :parts, dependent: :destroy

  accepts_nested_attributes_for :parts
  def name
  	return self.nombrecomercial_modelo
  end
end

app/models/family.rb
class Family < ApplicationRecord
	has_many :manufacturers , dependent: :destroy
	def name
		return self.nombre_familia
	end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :items, inverse_of: :invoice

  # Acepta atributos anidades de los items que contiene la factura
  accepts_nested_attributes_for :items 
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :invoice	
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  belongs_to :family
  def name
  	return self.nombre_fabricante
  end
end

app/models/mintest.rb
class Mintest < ApplicationRecord
	has_and_belongs_to_many :tests
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :provider
  has_many :parts , :dependent => :destroy

  accepts_nested_attributes_for :parts

  def name
  	fp = self.fecha_pedido.to_s
  	imp = self.valorPedido
  	str = ""

  	str << fp <<" : "<< imp	<<"€"
  	return str
  end
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :devise_model
  belongs_to :order
  has_and_belongs_to_many :tests

  accepts_nested_attributes_for :devise_model
  
  def name
  	return self.nombre_parte
  end
end

app/models/provider.rb
class Provider < ApplicationRecord
	def name
		return self.nombre_proveedor
	end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :build
  belongs_to :devise_model
  has_and_belongs_to_many :mintests

  #validaciones antes de poder escribir en la BD
  validates :devise_model, presence: true
  validates :build, presence: true
  validates :estado , acceptance: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_alert.html.erb
<div class="container-fluid">
 <div class="row">
  <% if notice.present? %>
   <div class="alert alert-info" role="alert"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
   <div class="alert alert-danger" role="alert"><%= alert %></div>
  <% end %>
 </div>
</div>

app/views/layouts/_footer.html.erb
<div class="col col-sm-12 bg-secondary fixed-bottom text-center">
		<p>2017 - Technologic Parts S.L</p>
</div>

app/views/layouts/_navbar.html.erb
<div class="col-md-12">
  <nav class="navbar navbar-expand-lg text-white bg-dark">
  <%= link_to 'Reparify' , root_path , :class => 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Clientes', customers_path , :class => 'nav-link'%>
      </li>
      <li class="nav-item">
                <%=link_to 'Facturacion', invoices_path, :class => 'nav-link'%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Taller
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Testeo', tests_path, :class => 'dropdown-item'%>
          <%= link_to 'Mini Tests', mintests_path, :class => 'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Configuración' , companies_path , :class => 'nav-link'%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</div>

app/views/layouts/_tables.html.erb
<table class="table table-sm table-striped">
  <thead class="thead-dark">
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
    <tr>
      <th scope="row">4</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
    <tr>
      <th scope="row">5</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reparify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

 <body>
  <div class="container-fluid">
    <div class="row">
      <%= render 'layouts/navbar' %>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= render 'layouts/alert' %>
        <%= yield %>
      </div>
    </div>  
    
  </div>

</body>
</html>